### ISSUE TITLE
Package installs with name mirmisc

### ISSUE THREAD

**Issue by kweav** [mirvie/mirmodels#1]
Because the DESCRIPTION file matches the DESCRIPTION file from the mirmisc package, this package does not install correctly. By changing the "Package" name on line 1 from mirmisc to mirmodels (locally), I was able to successfully install it.

**Comment by mirvie** [comment]
You are right. I will fix this now and let you know.

**Comment by mirvie** [comment]
The DESCRIPTION file was the wrong one. I have fixed this now.
Thanks a lot for letting me know.
